### ISSUE TITLE
Ability to Deprecate IPs

### ISSUE THREAD

**Issue by awickham10** [gomorpheus/morpheus-netbox-plugin#3]
Instead of deleting an IP from the IPAM, it would be nice to be able to deprecate that. For safety reasons, we set our IPs to deprecated for a period of time before an outside process comes through and reclaims them.

**Comment by BungeBash** [comment]
Updating the plugin to have a deprecate on delete flag at the integration level. This does cause the IP to still appear to remove from the UI (otherwise a major rewrite to the sync code would have to be done as well).  Next sync of that network it will come in as deprecated.  

Note: This should not cause duplicates with automated IP Addressing since we ask for next available from netbox.

**Comment by BungeBash** [comment]
Latest can be found on share. Grab the applicable to your version of Morpheus
https://share.morpheusdata.com/morpheus-netbox-plugin/about
